### ISSUE TITLE
pathview is not defined

### ISSUE THREAD

**Issue by perdakovich** [vimpostor/blobdrop#8] opened 2024-07-29 15:08 UTC
### Describe the bug

qrc:/src/qml/PathView.qml:46: ReferenceError: pathview is not defined

### To reproduce

blobdrop 2.1

Try to blobdrop multiple files with `-f gui` and choose "Drag all".

The same with `-f immediate` causes no error, but only the first one path  gets drag-and-dropped.

### Expected behavior

Succesful drag-and-drop of all files

**Comment by vimpostor** [comment] 2024-07-29 16:57
> Try to blobdrop multiple files with `-f gui` and choose "Drag all".

This is a regression in Qt, which I already fixed upstream: https://codereview.qt-project.org/c/qt/qtdeclarative/+/579204

> qrc:/src/qml/PathView.qml:46: ReferenceError: pathview is not defined

This warning is unrelated and has already been fixed in 9a75663a376e123b98c72c13b7063eb6cd07ba16

> The same with `-f immediate` causes no error, but only the first one path gets drag-and-dropped.

I can't reproduce this, for me `-f immediate` with multiple files drops all files. Are you sure this isn't working? If yes, which desktop environment and display server are you using, and which application are you dropping into?
Please also make sure to update to the latest version.

**Closed as completed** 2024-11-10 22:41 UTC
